// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpbYWr4UzonrM_c0mh83mD7jx31kAJ6MM',
    appId: '1:1037371543824:web:374ab9872d6cbfb1671595',
    messagingSenderId: '1037371543824',
    projectId: 'socialmediaapp-6db63',
    authDomain: 'socialmediaapp-6db63.firebaseapp.com',
    storageBucket: 'socialmediaapp-6db63.appspot.com',
    measurementId: 'G-EQT22XRQVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY2lY_zbQsbp7glvjcOh2LfHwtl50w_rI',
    appId: '1:1037371543824:android:d4c2681df299b780671595',
    messagingSenderId: '1037371543824',
    projectId: 'socialmediaapp-6db63',
    storageBucket: 'socialmediaapp-6db63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH0SLDNPDCyyy-VZL1TPP5xbScoD50hqY',
    appId: '1:1037371543824:ios:c904d85615c6260b671595',
    messagingSenderId: '1037371543824',
    projectId: 'socialmediaapp-6db63',
    storageBucket: 'socialmediaapp-6db63.appspot.com',
    iosBundleId: 'com.example.socialmediaapp',
  );
}
